name: location_picker_fz
description: A Flutter plugin which provides 'Location Picker' using Google Maps
  widget. (MB version)
version: 1.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^9.0.2
  google_api_headers: ^2.0.0
  google_maps_flutter: ^2.2.8
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^0.13.6
  provider: ^6.0.5
  tuple: ^2.0.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: null

false_secrets:
