name: location_picker_fz
description: A Flutter plugin which provides 'Location Picker' using Google Maps
  widget. (MB version)
version: 1.0.1

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: '>=3.19.5'

dependencies:
  flutter:
    sdk: flutter
  geolocator: ^11.0.0
  google_api_headers: ^4.0.0
  google_maps_flutter: ^2.6.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  http: ^1.2.1
  provider: ^6.1.2
  tuple: ^2.0.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  http: ^0.13.6

flutter: null

false_secrets:
